### ISSUE TITLE
<action> inside/pair/bound in markdown

### ISSUE THREAD

**Issue by chrisnicollo** [cursorless-dev/cursorless#1130]
When using the command <action> inside/pair/bound within a markdown file, the Cursorless extension may throw the error "Cannot read properties of undefined (reading 'apply')". Some markdown files experience this error, but not all.

**Comment by pokey** [comment]
Thanks for filing!  Could you please provide an example where it fails? I can't seem to reproduce the error 🤔

**Comment by chrisnicollo** [comment]
This file is giving me that issue. For some reason, if I delete a few lines of text and use the command again, it works. Then if I close and reopen the file in VSCode, the error comes up again. And if I delete a larger amount of text, the bug can go away fully, even if I close and reopen.

[bug.md](https://github.com/cursorless-dev/cursorless/files/9996331/bug.md)

**Comment by AndreasArvidsson** [comment]
Using that file I was able to recreate the problem. Looks like it originates in the tree sitter extension
```
TypeError: Cannot read properties of undefined (reading 'apply')
	at e.<computed> (c:\Users\Andreas\.vscode\extensions\pokey.parse-tree-0.26.4\node_modules\web-tree-sitter\tree-sitter.js:1:10533)
	at wasm://wasm/00182982:wasm-function[159]:0x7db9
	at e.<computed> (c:\Users\Andreas\.vscode\extensions\pokey.parse-tree-0.26.4\node_modules\web-tree-sitter\tree-sitter.js:1:10533)
	at wasm://wasm/00182982:wasm-function[141]:0x6b22
	at e.<computed> (c:\Users\Andreas\.vscode\extensions\pokey.parse-tree-0.26.4\node_modules\web-tree-sitter\tree-sitter.js:1:10533)
	at wasm://wasm/00182982:wasm-function[140]:0x67e3
	at wasm://wasm/000afe02:wasm-function[217]:0x245ba
	at Parser.parse (c:\Users\Andreas\.vscode\extensions\pokey.parse-tree-0.26.4\node_modules\web-tree-sitter\tree-sitter.js:1:35207)
	at openIfLanguageLoaded (c:\Users\Andreas\.vscode\extensions\pokey.parse-tree-0.26.4\out\extension.js:119:39)
	at getTreeForUri (c:\Users\Andreas\.vscode\extensions\pokey.parse-tree-0.26.4\out\extension.js:196:29)
	at Object.getNodeAtLocation (c:\Users\Andreas\.vscode\extensions\pokey.parse-tree-0.26.4\out\extension.js:236:24)
	at Object.getNodeAtLocation (c:\Users\Andreas\repositories\cursorless\packages\cursorless-vscode\dist\extension.js:41748:27)
	at LanguageDefinitions.getNodeAtLocation (c:\Users\Andreas\repositories\cursorless\packages\cursorless-vscode\dist\extension.js:29992:28)
	at processSurroundingPairCore (c:\Users\Andreas\repositories\cursorless\packages\cursorless-vscode\dist\extension.js:38330:32)
	at processSurroundingPair (c:\Users\Andreas\repositories\cursorless\packages\cursorless-vscode\dist\extension.js:38289:20)
	at processedSurroundingPairTarget (c:\Users\Andreas\repositories\cursorless\packages\cursorless-vscode\dist\extension.js:39022:24)
	at SurroundingPairStage.run (c:\Users\Andreas\repositories\cursorless\packages\cursorless-vscode\dist\extension.js:39014:12)
	at ContainingScopeStage.run (c:\Users\Andreas\repositories\cursorless\packages\cursorless-vscode\dist\extension.js:37255:75)
	at c:\Users\Andreas\repositories\cursorless\packages\cursorless-vscode\dist\extension.js:32887:49
	at Array.flatMap (<anonymous>)
	at c:\Users\Andreas\repositories\cursorless\packages\cursorless-vscode\dist\extension.js:32887:23
	at Array.forEach (<anonymous>)
	at processModifierStages (c:\Users\Andreas\repositories\cursorless\packages\cursorless-vscode\dist\extension.js:32886:18)
	at TargetPipeline.processPrimitiveTarget (c:\Users\Andreas\repositories\cursorless\packages\cursorless-vscode\dist\extension.js:32879:12)
	at TargetPipeline.processTarget (c:\Users\Andreas\repositories\cursorless\packages\cursorless-vscode\dist\extension.js:32766:21)
	at TargetPipeline.run (c:\Users\Andreas\repositories\cursorless\packages\cursorless-vscode\dist\extension.js:32754:29)
	at TargetPipelineRunner.run (c:\Users\Andreas\repositories\cursorless\packages\cursorless-vscode\dist\extension.js:32728:7)
	at c:\Users\Andreas\repositories\cursorless\packages\cursorless-vscode\dist\extension.js:36866:49
	at Array.map (<anonymous>)
	at CommandRunnerImpl.run (c:\Users\Andreas\repositories\cursorless\packages\cursorless-vscode\dist\extension.js:36865:39)
	at runCommand (c:\Users\Andreas\repositories\cursorless\packages\cursorless-vscode\dist\extension.js:39335:30)
	at async cursorless.command (c:\Users\Andreas\repositories\cursorless\packages\cursorless-vscode\dist\extension.js:41613:16)
	at async e.ExtHostCommands.h (c:\Users\Andreas\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:130656)
```
