### ISSUE TITLE
Cursorless record is borked for me

### ISSUE THREAD

**Issue by Leeft** [cursorless-dev/cursorless#1349]
I've updated to pnpm release (and just pulled in the latest updates to make sure, that changed the returned error a bit but not the fact it still is returning errors). VSCode reloaded too to update the extension.

```
rejected promise not handled within 1 second: Error: "Cursorless record" must be run from within cursorless directory
extensionHostProcess.js:100
stack trace: Error: "Cursorless record" must be run from within cursorless directory
	at TestCaseRecorder.<anonymous> (d:\Users\Lianna\Talon\cursorless\packages\cursorless-vscode\dist\extension.js:33606:15)
	at Generator.next (<anonymous>)
	at d:\Users\Lianna\Talon\cursorless\packages\cursorless-vscode\dist\extension.js:78:61
	at new Promise (<anonymous>)
	at __async (d:\Users\Lianna\Talon\cursorless\packages\cursorless-vscode\dist\extension.js:62:10)
	at TestCaseRecorder.promptSubdirectory (d:\Users\Lianna\Talon\cursorless\packages\cursorless-vscode\dist\extension.js:33604:12)
	at TestCaseRecorder.<anonymous> (d:\Users\Lianna\Talon\cursorless\packages\cursorless-vscode\dist\extension.js:33458:49)
	at Generator.next (<anonymous>)
	at d:\Users\Lianna\Talon\cursorless\packages\cursorless-vscode\dist\extension.js:78:61
	at new Promise (<anonymous>)
	at __async (d:\Users\Lianna\Talon\cursorless\packages\cursorless-vscode\dist\extension.js:62:10)
	at TestCaseRecorder.start (d:\Users\Lianna\Talon\cursorless\packages\cursorless-vscode\dist\extension.js:33450:12)
	at TestCaseRecorder.<anonymous> (d:\Users\Lianna\Talon\cursorless\packages\cursorless-vscode\dist\extension.js:33398:27)
	at Generator.next (<anonymous>)
	at d:\Users\Lianna\Talon\cursorless\packages\cursorless-vscode\dist\extension.js:78:61
	at new Promise (<anonymous>)
	at __async (d:\Users\Lianna\Talon\cursorless\packages\cursorless-vscode\dist\extension.js:62:10)
	at TestCaseRecorder.toggle (d:\Users\Lianna\Talon\cursorless\packages\cursorless-vscode\dist\extension.js:33393:12)
	at c.h (c:\Users\lianna\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:96:108784)
	at c.g (c:\Users\lianna\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:96:107674)
	at c.executeCommand (c:\Users\lianna\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:96:107574)
	at Object.executeCommand (c:\Users\lianna\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:117:30781)
	at CommandRunner.<anonymous> (c:\Users\lianna\.vscode\extensions\pokey.command-server-0.8.2\out\commandRunner.js:76:56)
	at Generator.next (<anonymous>)
	at fulfilled (c:\Users\lianna\.vscode\extensions\pokey.command-server-0.8.2\out\commandRunner.js:5:58)
```

**Comment by Leeft** [comment]
Oops dupe of #1341 ... thought that was merged

**Comment by pokey** [comment]
Yes that was the subject of https://github.com/cursorless-dev/cursorless/pull/1341, which got bogged down in a line endings quagmire

**Comment by pokey** [comment]
Eh I'm happy to leave this one open; having a paired issue and PR is not bad practice
