### ISSUE TITLE
new error: Language 'cpp' is still loading; please wait and try again

### ISSUE THREAD

**Issue by davidsgrogan** [cursorless-dev/cursorless#1512]
Saying "take func" or "change inside" in a C++ file gives me the error in the subject. These worked until very recently, I used them successfully sometime in the last day or two. Going to Panel->Output->Window, I see 

```
2023-05-31 17:18:49.247 [error] [Extension Host] LanguageStillLoadingError: Language 'cpp' is still loading; please wait and try again
    at getTreeForUri (/Users/dgrogan/.vscode/extensions/pokey.parse-tree-0.26.3/out/extension.js:202:27)
    at Object.getNodeAtLocation (/Users/dgrogan/.vscode/extensions/pokey.parse-tree-0.26.3/out/extension.js:236:24)
    at Object.getNodeAtLocation (/Users/dgrogan/.vscode/extensions/pokey.cursorless-0.26.691/extension.js:103:38609)
    at Mp.getNodeAtLocation (/Users/dgrogan/.vscode/extensions/pokey.cursorless-0.26.691/extension.js:81:99363)
    at processSurroundingPairCore (/Users/dgrogan/.vscode/extensions/pokey.cursorless-0.26.691/extension.js:85:515)
    at processSurroundingPair (/Users/dgrogan/.vscode/extensions/pokey.cursorless-0.26.691/extension.js:85:108)
    at processedSurroundingPairTarget (/Users/dgrogan/.vscode/extensions/pokey.cursorless-0.26.691/extension.js:85:9782)
    at Vc.run (/Users/dgrogan/.vscode/extensions/pokey.cursorless-0.26.691/extension.js:85:9681)
    at Nf.run (/Users/dgrogan/.vscode/extensions/pokey.cursorless-0.26.691/extension.js:84:20963)
    at ws.run (/Users/dgrogan/.vscode/extensions/pokey.cursorless-0.26.691/extension.js:81:104565)
    at Uf.run (/Users/dgrogan/.vscode/extensions/pokey.cursorless-0.26.691/extension.js:84:25669)
    at /Users/dgrogan/.vscode/extensions/pokey.cursorless-0.26.691/extension.js:81:107354
    at Array.flatMap (<anonymous>)
    at /Users/dgrogan/.vscode/extensions/pokey.cursorless-0.26.691/extension.js:81:107341
    at Array.forEach (<anonymous>)
    at processModifierStages (/Users/dgrogan/.vscode/extensions/pokey.cursorless-0.26.691/extension.js:81:107325)
    at Kg.processPrimitiveTarget (/Users/dgrogan/.vscode/extensions/pokey.cursorless-0.26.691/extension.js:81:107171)
    at Kg.processTarget (/Users/dgrogan/.vscode/extensions/pokey.cursorless-0.26.691/extension.js:81:105963)
    at Kg.run (/Users/dgrogan/.vscode/extensions/pokey.cursorless-0.26.691/extension.js:81:105751)
    at Lp.run (/Users/dgrogan/.vscode/extensions/pokey.cursorless-0.26.691/extension.js:81:105535)
    at /Users/dgrogan/.vscode/extensions/pokey.cursorless-0.26.691/extension.js:84:15905
    at Array.map (<anonymous>)
    at Df.<anonymous> (/Users/dgrogan/.vscode/extensions/pokey.cursorless-0.26.691/extension.js:84:15877)
    at Generator.next (<anonymous>)
    at /Users/dgrogan/.vscode/extensions/pokey.cursorless-0.26.691/extension.js:1:1520
    at new Promise (<anonymous>)
    at S (/Users/dgrogan/.vscode/extensions/pokey.cursorless-0.26.691/extension.js:1:1340)
    at Df.run (/Users/dgrogan/.vscode/extensions/pokey.cursorless-0.26.691/extension.js:84:15523)
    at /Users/dgrogan/.vscode/extensions/pokey.cursorless-0.26.691/extension.js:85:14613
    at Generator.next (<anonymous>)
    at a (/Users/dgrogan/.vscode/extensions/pokey.cursorless-0.26.691/extension.js:1:1378)
```

"take func" and "change inside" work in a javascript file.

Ideas?

**Comment by davidsgrogan** [comment]
Oh, in the time it took me to write this issue, the problem seems to have gone away. I ran into this error a bunch of times before filing though. Maybe my machine was just being very slow at the time for some reason and something was legitimately still loading.

Apologies for the noise. Closing.
