### ISSUE TITLE
Error messages in log on startup

### ISSUE THREAD

**Issue by pokey** [cursorless-dev/cursorless#2294]
Vscode extension host shows this on VSCode launch

```
TypeError: Cannot read properties of undefined (reading ‘query’)
	at t.create (.vscode-insiders/extensions/pokey.cursorless-0.28.1074/extension.cjs:127:270)
	at async W0.loadLanguage (.vscode-insiders/extensions/pokey.cursorless-0.28.1074/extension.cjs:128:1033)
```

Doesn't seem to affect behaviour, but worth removing log spam

**Comment by AndreasArvidsson** [comment]
Is this still present?

**Comment by pokey** [comment]
No I'm not seeing this anymore
