### ISSUE TITLE
Fix intermittent CI failures related to snippets

### ISSUE THREAD

**Issue by pokey** [cursorless-dev/cursorless#508]
Seems to fail when trying to load Cursorless built-in snippets:

```
       d:\a\cursorless-vscode\cursorless-vscode\src\test\suite\fixtures\recorded\languages\python\tryCatchWrapThis2:
     Error: Couldn't find snippet tryCatchStatement
  	at WrapWithSnippet.getTargetPreferences (d:\a\cursorless-vscode\cursorless-vscode\dist\extension.js:8167:13)
  	at CommandRunner.runCommand (d:\a\cursorless-vscode\cursorless-vscode\dist\extension.js:15404:71)
  	at processTicksAndRejections (internal/process/task_queues.js:93:5)
  	at async r._executeContributedCommand (d:\a\cursorless-vscode\cursorless-vscode\.vscode-test\vscode-win32-archive-1.63.2\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:95:31072)
```

See for example https://github.com/pokey/cursorless-vscode/runs/4944128667?check_suite_focus=true.

It's possible that this issue will be fixed by #304

**Comment by pokey** [comment]
Haven't seen this one in a while
